#language: shell

#Enable modern build platform
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/cache/clamav-dbs

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install clamav-daemon -qq"
  - "cp -f $HOME/cache/clamav-dbs/* /var/lib/clamav"
  - "sudo freshclam"
  - "cp -f /var/lib/clamav/* $HOME/cache/clamav-dbs"
  - "sudo service clamav-daemon start"

install:
  - "sudo mkdir -p /etc/clamav-unofficial-sigs"
  - "sudo cp -f config/master.conf /etc/clamav-unofficial-sigs/master.conf"
  - "sudo cp -f config/os.ubuntu.conf /etc/clamav-unofficial-sigs/os.conf"
  - "sudo cp -f .travis/tests/user.conf /etc/clamav-unofficial-sigs/user.conf"

script:
  - sudo sh -e .travis/ci-test.sh
