#language: shell

# Required environment variables from repository settings
#ci_securiteinfo_authorisation_signature=[secure]
#ci_malwarepatrol_receipt_code=[secure]
#ci_malwarepatrol_product_code=[secure]
#ci_malwarepatrol_list=[secure]
#ci_malwarepatrol_free=[secure]

# Notes
# caching the /var/lib/clamav/ as this saves +/-9mins of run time

#Enable modern build platform
#sudo: required
sudo: false
dist: trusty

#Enable Caching
cache:
  directories:
    - tmp/cache

before_install:
  - "apt-get update -qq"
  - "apt-get install clamav-daemon -qq"
  - "mkdir -p tmp/cache/"
  - "ls -laFh tmp/cache/clamav-dbs"
  - "rsync -rlptDv tmp/cache/  /var/lib/clamav/"
  - "chown -R clamav:clamav /var/lib/clamav"
  - "freshclam"
  - "ls -laFh /var/lib/clamav/"
  - "rsync -rlptDav /var/lib/clamav/ tmp/cache/"
  - "chown -R travis:travis tmp/cache"
  - "chmod -R 777 tmp/cache/"
  - "ls -laFh tmp/cache/clamav-dbs/"
  - "service clamav-daemon start"

install:
  - "mkdir -p /etc/clamav-unofficial-sigs"
  - "cp -f config/master.conf /etc/clamav-unofficial-sigs/master.conf"
  - "cp -f config/os.ubuntu.conf /etc/clamav-unofficial-sigs/os.conf"
  - "cp -f .travis/tests/user.conf /etc/clamav-unofficial-sigs/user.conf"

script:
  - "sh -e .travis/ci-test.sh"
