#language: shell

# Required environment variables from repository settings
#ci_securiteinfo_authorisation_signature=[secure]
#ci_malwarepatrol_receipt_code=[secure]
#ci_malwarepatrol_product_code=[secure]
#ci_malwarepatrol_list=[secure]
#ci_malwarepatrol_free=[secure]

# Notes
# caching the /var/lib/clamav/ saves +/-9mins of run time

#Enable modern build platform
sudo: required
dist: trusty

cache:
  directories:
    - tmp/cache/clamav-dbs

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install clamav-daemon -qq"
  - "sudo mkdir -p tmp/cache/clamav-dbs"
  - "sudo rsync -rlptDv tmp/cache/clamav-dbs/  /var/lib/clamav/"
  - "sudo chown -R clamav:clamav /var/lib/clamav"
  - "sudo freshclam"
  - "sudo rsync -rlptDav /var/lib/clamav/ tmp/cache/clamav-dbs/"
  - "sudo chomd -R 777 tmp/cache/"
  - "sudo service clamav-daemon start"

install:
  - "sudo mkdir -p /etc/clamav-unofficial-sigs"
  - "sudo cp -f config/master.conf /etc/clamav-unofficial-sigs/master.conf"
  - "sudo cp -f config/os.ubuntu.conf /etc/clamav-unofficial-sigs/os.conf"
  - "sudo cp -f .travis/tests/user.conf /etc/clamav-unofficial-sigs/user.conf"

script:
  - sudo sh -e .travis/ci-test.sh
