language: bash

# Enable modern build platform, not container based.
sudo: required
dist: trusty

before_install:
  - "sudo add-apt-repository ppa:teward/clamav -y"
  - "sudo apt-get -qq update"
  - "sudo apt-get install -qq ca-certificates wget rsync clamav-daemon"
  - "sudo cp -f .t/tests/bytecode.cvd /var/lib/clamav/bytecode.cvd"
  - "sudo chown -R clamav:clamav /var/lib/clamav"
  - "sudo service clamav-daemon start"

install:
  - "sudo mkdir -p /etc/clamav-unofficial-sigs"
  - "sudo cp -f config/master.conf /etc/clamav-unofficial-sigs/master.conf"
  - "sudo cp -f config/os.ubuntu.conf /etc/clamav-unofficial-sigs/os.conf"
  - "sudo cp -f .t/tests/user.conf /etc/clamav-unofficial-sigs/user.conf"
  - "sudo cp -f clamav-unofficial-sigs.sh /usr/sbin/clamav-unofficial-sigs"

script:
  - sudo sh -e .t/ci-test.sh

addons:
  code_climate:
    repo_token: 270be84579d01fcbe78b21b91719c2c55cd627f074c8abb83699a8319c980b60
